<h2>Registrate usando este formulario</h2>

<?php echo Phalcon\Tag::formLegacy('signup/register');?>

    <p>
        <label for="Nombre">Name</label>
        <?php echo Phalcon\Tag::textField("nombre"); ?>
    </p>

    <p>
        <label for="Correo">E-Mail</label>
        <?php echo Phalcon\Tag::textField("correo"); ?>
    </p>

    <p>
        <?php echo Phalcon\Tag::submitButton([
        'Registrarse',
        'class' => 'btn btn-primary'
        ]); ?>
    </p>

<?php echo Phalcon\Tag::endForm(); ?>