<?php

echo "<h1>Usuarios</h1>";

echo PHP_EOL;

echo PHP_EOL;

echo Phalcon\Tag::linkTo(
    [
        'signup',
        '¡Registrate aqui!',
        'class' => 'btn btn-primary',
    ]
);

if ($usuarios->count() > 0) {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>#</th>
            <th>Nombre</th>
            <th>Correo</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td colspan="3">Cantidad de usuarios: <?php echo $usuarios->count(); ?></td>
        </tr>
        </tfoot>
        <tbody>
        <?php foreach ($usuarios as $usuario) { ?>
            <tr>
                <td><?php echo $usuario->id; ?></td>
                <td><?php echo $usuario->nombre; ?></td>
                <td><?php echo $usuario->correo; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
    <?php
}